;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comint-delchar-or-maybe-eof
        haskell-indentation-common-electric-command
        hydra-pair/body
        hydra-pair/sp-rewrap-sexp
        hydra-pair/sp-splice-sexp
        hydra-text/crux-kill-whole-line
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/body
        hydra-multiple-cursors/mc/insert-numbers-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-text/body
        ))
