;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-text/body
        hydra-text/crux-kill-whole-line
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/mc/mark-all-like-this
        ))
