- name: Utilities
  hosts: all
  gather_facts: yes
  become: yes
  tags: utils
  vars:
    src_dir: "{{ lookup('env', 'HOME') }}/src"
  pre_tasks:
    - name: create src directory
      file:
        path: "{{ src_dir }}"
        state: directory
    - name: update cache
      package:
        update_cache: yes
  tasks:
    - name: clone Yay (AUR Helper)
      become: no
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: "{{ src_dir }}/yay"
        version: master
      when: ansible_facts['os_family'] == "Archlinux"
    - name: install yay
      command:
        chdir: "{{ src_dir }}/yay"
        cmd: makepkg -si
      when: ansible_facts['os_family'] == "Archlinux"

- name: Fonts
  hosts: all
  tags: fonts
  become: yes
  tasks:
    - name: install fonts
      pacman:
        name: ttf-dejavu,ttf-unifont,ttf-liberation,noto-fonts
        state: present
