#!/usr/bin/env sh

nix-channel --add https://github.com/nix-community/home-manager/archive/release-21.05.tar.gz home-manager
nix-channel --update

nix-shell '<home-manager>' -A install

nix-shell -p stow --command "stow nix"
