= dotfiles
:toc:

== Stow

Mainly I structure my modules follow their paths starting from
`+$HOME+`. To activate the module, symlink the corresponding folder to
`+$HOME+`.

This task is done by
https://www.gnu.org/software/stow/manual/stow.html[GNU Stow].

[source,fish]
....
stow <module>
....

Not every module here can be stowed though.

== Linux

Some distros I’m using for my personal machine:

* https://www.opensuse.org/[OpenSUSE Tumbleweed]
** Rolling released.
** System recovery and snapshot with
https://doc.opensuse.org/documentation/leap/reference/html/book-reference/cha-snapper.html[Snapper]
and https://en.wikipedia.org/wiki/Btrfs[btrfs]
** https://yast.opensuse.org/[YaST] is awesome.
* https://getfedora.org/[Fedora]
** Supports a wide range of hardware.
** Bleeding edge packages.
** btrfs is the default filesystem since Fedora 36.
* https://archlinux.org/[Arch]:
** Rolling released.
** Total control of my system. KISS (Keep It Simple, Stupid).
** Arch’s https://wiki.archlinux.org/[wiki] is awesome.
** Have fun ricing my desktop.

=== Guix

I use https://guix.gnu.org/[Guix] as my package manager, together with
the official package manager (i.e. Fedora’s `+dnf+`)

* Stow `+guix+` first.
* To make packages update effective:

[source,fish]
----
guix home reconfigure ~/.config/guix/home-configuration.scm
----

* To describe generations:

[source,fish]
----
guix home describe
----

== BSD

_TBD_

== Mac

https://www.macports.org/[MacPorts] and https://nixos.org/[Nix] are used to manage packages.

=== MacPorts

Mainly used for installing the text editor (Emacs) and packages which I cannot simply install with Nix.

=== Nix

* Use the `+nix-installer+` from https://zero-to-nix.com/[Determinate Systems] to install Nix on Mac.

[source,bash]
----
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
----

* Install https://nix-community.github.io/home-manager/index.html[home-manager]:

[source,bash]
----
# with an unstable channel
nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager

# with a stable channel
nix-channel --add https://github.com/nix-community/home-manager/archive/release-24.11.tar.gz home-manager
----

[source,bash]
----
nix-channel --update
nix-shell '<home-manager>' -A install
----

* Shell are not managed with `+home-manager+` though, for stability reason.

* Add +nixpkgs+ channels:

[source,bash]
----
nix-channel --add https://channels.nixos.org/nixpkgs-24.05-darwin nixpkgs
nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs-unstable
nix-channel --update
----

* When you need to make change to the packages, edit `+~/.config/home-manager/home.nix+` and:

[source,bash]
----
home-manager switch
----

==== Symlink with `+home-manager+`

* `+stow+` is used when changes are made often: e.g. `+fish+`, `+vim+`.
* Otherwise, some modules are managed and symlinked with
`+home-manager+`. Check what modules are managed with `+home-manager+`
in `+home-manager/home.nix+`:

[source,nix]
----
home.file = {
  ...
}
----

==== Rollbacks

* List generations:

[source,bash]
----
home-manager generations
----

* Perform the rollback:

[source,bash]
----
/nix/store/...-home-manager-generation/activate
----

==== Issues

* Broken `+home-manager+`? Update Nix’s channel to pull fixes and
install `+home-manager+` again:

[source,bash]
----
nix-channel --add <fixed-channel> home-manager
nix-channel --update

home-manager switch
----

== Shell

My default shell is Zsh with https://zimfw.sh/docs/install/[Zim].

This dotfiles contains the universal configuration: `stow zsh`. It will put the
universal default configuration inside +~/.config/zsh/zsh.sh~.

Create custom file for each machine: `+~/customs/zsh.sh+`.

After the installation of Zim, in your +~/.zhsrc+:

[source,bash]
----
# ------------------------------
# Fixed
# ------------------------------

[[ -f $HOME/.config/zsh/zsh.sh ]]  && source $HOME/.config/zsh/zsh.sh

# ------------------------------
# Custom
# ------------------------------

[[ -f $HOME/customs/zsh.sh ]]  && source $HOME/customs/zsh.sh
----


== Emacs

I decided to switch (and possibly contribute) to
https://github.com/hlissner/doom-emacs/[doom-emacs] instead of writing
my vanilla Emacs configurations.

Install:

[source,bash]
----
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d
~/.emacs.d/bin/doom install
----

Then +stow emacs+.

I want to contribute and learn best practice from community, at least
until I’m confident enough to maintain my own configurations.

My Doom Emacs’ configuration lives in `+emacs/.doom.d+`.

=== Issues

* Broken icons in the modeline: `+M-x+` to install:

[source,emacs-lisp]
----
nerd-icons-install-fonts
----

== Vim

* Create custom file for each machine: `+~/customs/custom.vim+`. For example:

....
colorscheme alduin
....

== Python

A lot of tools are installed with Python `+pip+`. I use
https://github.com/pyenv/pyenv[pyenv] to manage my Python environments.

* To configure `+pyenv+` with Fish shell:

[source,fish]
----
set -Ux PYENV_ROOT $HOME/.pyenv
fish_add_path $PYENV_ROOT/bin
pyenv init - | source
----

* To install and use a Python version globally:

[source,fish]
----
pyenv install 3.10
pyenv global <version>
----

== Ruby

I use https://github.com/rbenv/rbenv[rbenv] to manage my Ruby
environments.

* To configure `+rbenv+` with Fish shell:

[source,fish]
----
fish_add_path $HOME/.rbenv/shims
status --is-interactive; and rbenv init - fish | source
----

* To install and use a Ruby version globally:

[source,fish]
----
rbenv install 3.2.2
rbenv global <version>
----


== Themes

Below is an awesome list of themes done in style. All are eye-care
themes.

* https://www.nordtheme.com/[Nord]
* https://ethanschoonover.com/solarized/[Solarized]
* https://github.com/john2x/plan9-theme.el[Plan9/Acme]

== Mouse

=== Logitech MX Master 3

* Driver on Linux: https://github.com/PixlOne/logiops[logiops]
** Key codes can be found
https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h[here]
* Put the configuration in `+mx-master-3/<desktop>/logid.cfg+` at
`+/etc/logid.cfg+`:
* Start/Enable the service:

[source,bash]
----

sudo systemctl enable --now logid
----

* Restart the service:

[source,bash]
----
sudo systemctl restart logid
----

== Firefox

* I follow recommendations from
https://github.com/yokoffing/BetterFox[Betterfox]
* Note that editing `+about:config+` won’t take effect if you have
`+user.js+` inside your profiles. `+user.js+` will reset all of your
changes when start a new browser.
* Mac:

[source,fish]
----
ln -s $PWD/firefox/user.js "$HOME/Library/Application Support/Firefox/Profiles/"
----

* Linux:

[source,fish]
----
ln -s $PWD/firefox/user.js (readlink -f (ls -d $HOME/.mozilla/firefox/*.default | head -n 1))/
----

== uBlock Origin Filter Lists

- Go to *Options > Filter Lists > Annoyances* and turn on all of them. Optionally, you can turn on Cloud Storage sync (https://github.com/gorhill/uBlock/wiki/Cloud-storage[refer]).

- Some additional personal filters list:

```
accounts.google.com/gsi/iframe
```
