#
# shell
#
brew "fish"
# https://github.com/cheat/cheat
brew "cheat"
brew "stow"
brew "ripgrep"
brew "nushell"
brew "direnv"
brew "jump"
brew "tmux"
brew "fd"
brew "bat"
brew "fzf"
brew "ncdu"
brew "jq"
brew "yq"
brew "jo"
brew "wget"
brew "htop"
brew "watchman"

#
# editor
#
cask "emacs"
brew "aspell"
brew "gnu-indent"

#
# dev
#
brew "cmake"
brew "nasm"

#
# ops
#
brew "pass"
brew "borgbackup"
brew "terraform"
cask "google-cloud-sdk"
brew "kubectx"
brew "minikube"
brew "nmap"
brew "rclone"
brew "telnet"

tap "turbot/tap"
brew "steampipe"

#
# os
#
brew "qemu"
cask "vagrant"

#
# languages
#
brew "go"
brew "julia"
brew "graphviz"
