#!/usr/bin/env bb
(require '[babashka.process :refer [process $ check]])

(defn help []
  (println "Usage: _emacs start|stop|restart"))

(defn new-frame []
  (-> (process '[emacsclient --create-frame &]) check))

(defn start []
  (-> (process '[emacs --daemon]) check))

(defn stop []
  (-> (process '[emacsclient -e "(save-buffers-kill-emacs)"]) check))

(defn restart []
  (stop)
  (start))

(if (zero? (count *command-line-args*))
  (new-frame)
  (let [cmd (first *command-line-args*)]
    (cond
      (= cmd "start") (start)
      (= cmd "stop") (stop)
      (= cmd "restart") (restart)
      :else (help))))
