#!/usr/bin/env fish
# Backup local external storage to GCP Cloud Storage.
# -d flag is passed in `gsutil` to mirror source and destination.
#
# Usage:
#
# 1) Default show progress
#
#   $ _backup_gcp
#
# 2) Run in quiet mode, without reporting progress. Only errors are reported.
# Suitable for cron job.
#
#  $ _backup_gcp -q
#

set -x BACKUP_DIR /Volumes/MacBackup/MacHome
set GCP_BUCKET gs://hiepph-mac/MacHome

function backup_gcp
    argparse q/quiet -- $argv

    echo "Backing up $BACKUP_DIR to $GCP_BUCKET..."
    if set -q _flag_quiet
        gsutil -q -m rsync -d -r $BACKUP_DIR $GCP_BUCKET
    else
        gsutil -m rsync -d -r $BACKUP_DIR $GCP_BUCKET
    end
end

backup_gcp $argv

echo "DONE"
