#!/bin/zsh
# Backup local files to an local external storage.
# Note: borg create --stats output to stderr

BACKUP_DIR=/Volumes/MacBackup/MacHome
BACKUP_ID=$(date +%Y-%m-%d)

TARGET_DIRS=(
    "$HOME/.config"
    "$HOME/.ssh"
    "$HOME/Books"
    "$HOME/Code"
    "$HOME/Courses"
    "$HOME/Projects"
    "$HOME/Vault"
    "$HOME/Documents"
    "$HOME/Pictures"
)

echo ">>> Backup $BACKUP_ID\n" 1>&2

if [ -z "$BORG_PASSPHRASE" ]; then
    export BORG_PASSPHRASE=$(pass show borg/MacBackup)
fi

if [ -d "$BACKUP_DIR" ]; then
   if borg check $BACKUP_DIR::$BACKUP_ID ; then
      echo ">>> Backup existed. Deleting old record..."
      borg delete $BACKUP_DIR::$BACKUP_ID
   fi

   borg create -v --stats $BACKUP_DIR::$BACKUP_ID $TARGET_DIRS
   STATUS=$?

   if [ $STATUS -eq 0 ]; then
    echo ">>> Pruning..."
    borg prune -v --list --keep-within=7d --keep-weekly=3 --keep-montly=-1 $BACKUP_DIR
   fi
else
    echo "$BACKUP_DIR doesn't exist. Skip back up." 1>&2
fi
