#!/bin/zsh
# Backup local external storage to S3.

BACKUP_DIR=/Volumes/MacBackup/MacHome
S3_BUCKET=s3://hiepph-mac/MacHome

export AWS_ACCESS_KEY_ID=$(pass show aws/personal/ACCESS_KEY)
export AWS_SECRET_ACCESS_KEY=$(pass show aws/personal/SECRET_KEY)

aws s3 sync ${BACKUP_DIR} ${S3_BUCKET} --delete

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
