#
# Editor
#

# ref: https://github.com/d12frosted/homebrew-emacs-plus
tap "d12frosted/emacs-plus"
brew "emacs-plus@29"

#
# Languages
#
brew "pyenv"
brew "rbenv"
brew "ruby-build" # rbenv plugin

#
# dots
#
brew "fish"
brew "nushell"
brew "dust" # ncdu, in rust
brew "borgbackup"

#
# ops
#
brew "pulumi" # IaC
