#!/bin/zsh

# Note: borg create --stats output to stderr

BACKUP_DIR=/Volumes/MacBackup/MacHome
BACKUP_ID=$(date +%Y-%m-%d.%s)

echo "\n***\nBackup $BACKUP_ID\n" 1>&2

if [ -d "$BACKUP_DIR" ]; then
   BORG_PASSPHRASE=$(pass show borg/MacBackup) \
            borg create --exclude '.git/' -v --stats \
            $BACKUP_DIR::$BACKUP_ID \
            ~/Code \
            ~/.config \
            ~/.ssh \
            ~/Courses \
            ~/Projects \
            ~/Vault
else
    echo "$BACKUP_DIR doesn't exist. Skip back up." 1>&2
fi
