#!/bin/zsh

# Note: borg create --stats output to stderr

BACKUP_ID=$(date +%Y-%m-%d)

echo "\n***\nBackup $BACKUP_ID\n" 1>&2

BORG_PASSPHRASE=$(pass show borg/MacBackup) \
     borg create --exclude '.git/' -v --stats \
     /Volumes/MacBackup/MacHome::$BACKUP_ID \
     ~/Code \
     ~/.config \
     ~/.ssh \
     ~/Courses \
     ~/Projects \
     ~/Vault
