#!/usr/bin/env fish

#
# trim clears all leading, trailing spaces and multiple spaces between words
#
# EXAMPLES
# $ _trim "    a    long string"
# #=> "a long string"
#
# $ echo "    another long   string" | _trim
# #=> "another long string"
#

function trim
    sed 's/ *//' | tr -s ' '
end

if test $argv[1]
   echo $argv[1] | trim
else
    trim
end
