- name: backup
  hosts: local
  tags:
    - backup
  vars_files:
    - vars.yml
  tasks:
    - name: Pull borg passphrase from pass
      shell: pass show borg/MacBackup
      register: borg_passphrase
    - name: Add borg passpharse to cron
      cron:
        env: yes
        name: BORG_PASSPHRASE
        job: "{{ borg_passphrase.stdout }}"
    - name: Add target email
      cron:
        env: yes
        name: MAILTO
        job: "hiepph@tuta.io"
    - name: Backup locally daily
      cron:
        name: "Backup local daily"
        minute: "30"
        hour: "22"
        job: "{{ home_dir }}/backup/_backup_local"
    - name: Backup to GCP daily
      cron:
        name: "Backup gcp daily"
        minute: "30"
        hour: "10"
        job: ".nix-profile/bin/fish -c '{{ home_dir }}/backup/_backup_gcp --quiet'"

- name: install fonts
  hosts: local
  tags:
    - fonts
  vars_files:
    - vars.yml
  tasks:
    - name: source code pro
      block:
        - get_url:
            url: " https://github.com/adobe-fonts/source-code-pro/releases/download/2.038R-ro%2F1.058R-it%2F1.018R-VAR/TTF-source-code-pro-2.038R-ro-1.058R-it.zip"
            dest: "{{ download_dir }}/source-code-pro.zip"
          register: downloaded_file
        - unarchive:
            src: "{{ downloaded_file.dest }}"
            dest: "{{ home_dir }}/Library/Fonts"

- name: shell configuration
  hosts: local
  tags:
    - shell
  vars_files:
    - vars.yml
  vars:
    - completions_dir: "{{ home_dir }}/.config/fish/completions"
  tasks:
    - name: make sure fish completions dir existed
      stat:
        path: "{{ completions_dir }}"
      register: comp_dir

    - name: add docker completion
      get_url:
        url: "https://raw.githubusercontent.com/docker/cli/master/contrib/completion/fish/docker.fish"
        dest: "{{ completions_dir }}/docker.fish"
      when: comp_dir.stat.exists
