- hosts: all
  name: install Pyenv (for managing Python environments)
  tags:
    - pyenv
  tasks:
    # TODO: make sure .pyenv doesn't exist
    - name: Use the installation script
      shell: curl https://pyenv.run | bash
    - name: make sure we have lib OpenSSL
      dnf:
        name:
          - make
          - gcc
          - patch
          - zlib-devel
          - bzip2
          - bzip2-devel
          - readline-devel
          - sqlite
          - sqlite-devel
          - openssl-devel
          - tk-devel
          - libffi-devel
          - xz-devel
          - libuuid-devel
          - gdbm-libs
          - libnsl2
        when: ansible_facts['distribution'] == 'Fedora'
      # TODO:
      # shell: pyenv install 3.11
      # shell: pyenv global 3.11

- hosts: all
  name: Install essential toolboxes
  tags:
    - tools
  tasks:
    # TODO: make sure `pyenv` exists

    - name: install useful packages
      pip:
        name:
          - 'click' # CLI
          - 'borgmatic' # backup
          - 'pip-autoremove' # remove a package together with unused dependencies
          - 'httpie' # curl alternatives
          - 'speedtest-cli'
          - 'jc' # everything to json
